import{S as p,i as a}from"./assets/vendor-f3f87f24.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const m=o=>o.map(({webformatURL:r,tags:i,largeImageURL:n,views:e,comments:t,downloads:s,likes:u})=>`<li><a href=${n}> 
        <img src=${r} alt=${i} width="300"></a>
        <div>
        <p>likes: ${u}</p>
        <p>likes: ${s}</p>
        <p>likes: ${t}</p>
        <p>likes: ${e}</p></div>
      </li>`).join(""),f="42467194-b110ad867f5196c7e5e9f8f90",d="https://pixabay.com/api/",h=o=>fetch(`${d}?key=${f}&q=${o}&image_type=photo&orientation=horizontal=horizontal&safesearch=true`).then(r=>{if(r.ok)return r.json()}),y=document.querySelector(".searchForm"),l=document.querySelector(".loader"),c=document.querySelector(".gallery");let g=new p(".gallery a",{});y.addEventListener("submit",b);function b(o){o.preventDefault();const r=o.target.elements.searchQuery.value.trim();if(!r){a.error({title:"Error",message:"input please your request",position:"topRight",timeout:3e3,maxWidth:"400px"});return}l.style.display="inline-block",c.innerHTML="",o.target.elements.searchQuery.value="",h(r).then(({hits:i})=>{if(!i.length){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3e3,maxWidth:"400px"});return}const n=m(i);c.innerHTML=n,g.refresh()}).catch(i=>a.error({title:"Error",message:i.message,position:"topRight",timeout:3e3,maxWidth:"400px"})).finally(()=>{l.style.display="none",console.log("none")})}
//# sourceMappingURL=commonHelpers.js.map
